baseURL = "https://mises.in.ua/"
languageCode = "ru-ru"
title = "Liberty Education Project"
copyright = "Liberty Education Project"
disableKinds = ["section"]
theme = "diary"
googleAnalytics = "UA-167974269-1"

[params]
subtitle = "Knowledge Is Freedom"
enableGitalk = false

[params.gitalk]
  owner = "user"
  repo = "repo name"
  client_id = "your client id"
  client_secret = "your client secret"
[taxonomies]
   tag = "tags"
#   author = "authors"
#   category = "categories"
