baseURL = "https://mises.in.ua/"
languageCode = "ru-ru"
title = "Liberty Education Project"
copyright = "Liberty Education Project"
disableKinds = ["section"]
theme = "diary"
googleAnalytics = "UA-167974269-1"

[params]
subtitle = "Knowledge Is Freedom"
enableGitalk = false

[taxonomies]
   tag = "tags"
#   author = "authors"
#   category = "categories"
